friday afternoon bugfix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,7 +21,8 @@ jobs:
       with:
         submodules: recursive
         repository: cisco-open/nasp
-        path: nasp  
+        path: nasp
+        fetch-depth: 0
 
     - name: Setup Golang with cache
       uses: magnetikonline/action-golang-cache@v4
@@ -55,7 +56,10 @@ jobs:
 
     - name: Build Nasp CLI
       working-directory: nasp
-      run: make build
+      run: |
+        echo "checking out ${GITHUB_HEAD_REF} branch"
+        git checkout ${GITHUB_HEAD_REF} || echo "branch not found"
+        make build
 
     # - name: Setup upterm session
     #   uses: lhotari/action-upterm@v1
@@ -67,31 +71,38 @@ jobs:
       working-directory: nasp-kernel-module
       timeout-minutes: 1
       run: |
-        sudo ../nasp/build/nasp agent &
-        go run test/file-server.go &
+        touch /tmp/nasp.log /tmp/file-server.log /tmp/python.log
+        echo "Run processes"
+        sudo ../nasp/build/nasp agent --config ../nasp/config.yaml --rules-path $(pwd)/../nasp/rules.d > /tmp/nasp.log &
+        go run test/file-server.go >/tmp/file-server.log &
         docker run -d --rm -p 8080:80 nginx
         sleep 2
 
-        # Test downloading a bigger file
+        echo "Test downloading a bigger file"
         truncate -s 2M bigfile.o
         curl -v -o /tmp/bigfile_downloaded.o http://localhost:8000/bigfile.o
 
-        # Test uploading this file
+        echo "Test uploading this file"
         curl -v -F "bigfile_downloaded.o=@/tmp/bigfile_downloaded.o" http://localhost:8000/upload
         diff bigfile.o bigfile_downloaded.o
 
-        # Test bearssl with non-bearssl compatibility
-        python3 -m http.server 7000 &
+        echo "Test bearssl with non-bearssl compatibility"
+        python3 -m http.server 7000 >/tmp/python.log &
         sleep 1
         curl -k -v https://localhost:7000/
 
-        # Test sendfile with NGiNX
+        echo "Test sendfile with NGiNX"
         curl -v http://localhost:8080
 
-        sudo dmesg -T | tail -100
-
+        echo "Stop processes"
         sudo kill -9 $(jobs -p)
         sudo pkill -9 nasp
+
+    - name: Print logs
+      if: always()
+      run: |
+        cat /tmp/nasp.log /tmp/file-server.log /tmp/python.log
+        sudo dmesg -T
 
     - name: Cleanup module
       run: sudo modprobe -r nasp
