ci: excercise (only) DKMS during the builds (#76)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,14 +32,25 @@ jobs:
       working-directory: nasp-kernel-module
       run: make setup-vm
 
-    - name: Build the kernel module
+    - name: Build with DKMS
       working-directory: nasp-kernel-module
-      run: make -j$(nproc)
+      run: |
+        sudo cp -r . /usr/src/nasp-0.1.0/
+        sudo dkms add -m nasp -v 0.1.0
+        if sudo dkms build -m nasp -v 0.1.0; then
+          echo "DKMS build succeeded"
+        else
+          echo "DKMS build failed"
+          cat /var/lib/dkms/nasp/0.1.0/build/make.log
+          exit 1
+        fi
+        sudo dkms install -m nasp -v 0.1.0
 
     - name: Run the kernel module
       working-directory: nasp-kernel-module 
       run: |
-        make insmod
+        sudo modprobe tls
+        sudo modprobe nasp
         sudo dmesg -T
 
     - name: Build Nasp CLI
@@ -62,16 +73,17 @@ jobs:
         sleep 2
 
         # Test downloading a bigger file
-        curl -v -o /tmp/opa_downloaded.o http://localhost:8000/opa.o
+        truncate -s 2M bigfile.o
+        curl -v -o /tmp/bigfile_downloaded.o http://localhost:8000/bigfile.o
 
         # Test uploading this file
-        curl -v -F "opa_downloaded.o.o=@/tmp/opa_downloaded.o" http://localhost:8000/upload
-        diff opa.o opa_downloaded.o
+        curl -v -F "bigfile_downloaded.o=@/tmp/bigfile_downloaded.o" http://localhost:8000/upload
+        diff bigfile.o bigfile_downloaded.o
 
         # Test bearssl with non-bearssl compatibility
         python3 -m http.server 7000 &
         sleep 1
-        curl -k -v -o /dev/null https://localhost:7000/opa.o
+        curl -k -v https://localhost:7000/
 
         # Test sendfile with NGiNX
         curl -v http://localhost:8080
@@ -82,20 +94,4 @@ jobs:
         sudo pkill -9 nasp
 
     - name: Cleanup module
-      working-directory: nasp-kernel-module
-      run: make rmmod
-
-    - name: Test DKMS
-      working-directory: nasp-kernel-module
-      run: |
-        sudo cp -r . /usr/src/nasp-0.1.0/
-        sudo dkms add -m nasp -v 0.1.0
-        if sudo dkms build -m nasp -v 0.1.0; then
-          echo "DKMS build succeeded"
-        else
-          echo "DKMS build failed"
-          cat /var/lib/dkms/nasp/0.1.0/build/make.log
-          exit 1
-        fi
-        sudo dkms install -m nasp -v 0.1.0
-        sudo dmesg -T
+      run: sudo modprobe -r nasp
